name = "da-backup-launcher"
main = "src/index.js"
compatibility_date = "2024-01-01"

[triggers]
crons = ["0 0 * * *"]  # Every day at 1 AM CET (midnight UTC)

# Default / dev (e.g. wrangler dev, wrangler deploy without -e)
[vars]
ACCOUNT_ID = "852dfa4ae1b0d579df29be65b986c101"
SOURCE_BUCKET = "acapt-content"
DESTINATION_BUCKET = "acapt-content-backup"

[env.production]
name = "da-backup-launcher"

[env.production.triggers]
crons = ["0 0 * * *"]  # Every day at 1 AM CET (midnight UTC)

[env.production.vars]
ACCOUNT_ID = "852dfa4ae1b0d579df29be65b986c101"
SOURCE_BUCKET = "aem-content"
DESTINATION_BUCKET = "aem-content-backup"
